### ISSUE TITLE
STM32 ARDUINO  'EepromStream' does not name a type

### ISSUE THREAD

**Issue by MINI-Qiang** [bblanchon/ArduinoStreamUtils#11]
https://github.com/stm32duino/Arduino_Core_STM32
https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json
my test STM32 “EepromStream”  requite “'EepromStream' does not name a type”  May not support

**Comment by bblanchon** [comment]
Hi @MINI-Qiang,

I just fix the support for STM32.
Please be aware that STM32 doesn't have EEPROM on board: the EEPROM library uses an emulation base on Flash memory.
Unfortunately, this library doesn't use a buffer (as in ESP8266 and ESP32), so it's going to be quite slow.

I'll publish this change in version 1.6.1 very soon.

Best regards,
Benoit
