### ISSUE TITLE
Compatibility nrf52840 

### ISSUE THREAD

**Issue by sergioxdev** [bblanchon/ArduinoStreamUtils#13]
Hi Guys

someone has already tested compatibility with the nrf52840, or the nrf52x family

Thanks in advance for any replies

**Comment by bblanchon** [comment]
Hi,

I don't own a board with this microcontroller so I cannot be 100% sure, but it looked closely a the [core for nRF52](https://github.com/adafruit/Adafruit_nRF52_Arduino) and I'm confident everything should work fine (except the Eeprom classes, obviously).

Please let me know if you find any problems.

Best regards,
Benoit
