### ISSUE TITLE
Lots of TCP Window Full and TCP Zero Window while receiving a file via HTTP

### ISSUE THREAD

**Issue by dplhenterprises** [bblanchon/ArduinoStreamUtils#23]
Benoît,

I'm using your JSON library and Stream Utils in a network µController project.
Awesome work on the JSON library, by the way. 

Environment:
- Adafruit Feather M4 Express (192K RAM, 512KB Flash, https://www.adafruit.com/product/3857)
- Adafruit MusicMaker FeatherWing (https://www.adafruit.com/product/3436)
- Silicognition Ethernet with PoE FeatherWing (https://hackaday.io/project/168356-poe-featherwing)
- PlatformIO in VSCode on a Mac

I'm using both ReadBufferingClient and WriteBufferingClient with 512KB buffers.

WriteBufferingClient is working great! The M4 can send a largish chunk of data to the server via an HTTP Put with only one TCP data packet (plus the SYNs, ACKs, etc.) Prior to using WriteBufferingClient the data was being broken up into numerous data packets.

Receiving data, though isn't working so well. I'm using a ReadBufferingClient with a 512-byte buffer. Even so, the incoming data is broken into lots of packets and Wireshark reports lots of TCP WIndow Full and TCP Zero Window events.

The incoming data is about 47KB and is retrieved with an HTTP GET using the Arduino EthernetClient.

There is actually an additional custom HttpClient class between the EthernetClient and ReadBufferingClient. All of its methods (read, available, etc.), simply call the underlying EthernetClient method and return the results.

The PoE FeatherWing has a Wiznet W5500 on it which is supposed to have 2KB buffers by default. Seems like this should work reasonably well.

Have you run into this? 
Any suggestions?

TIA,
Dave

**Comment by bblanchon** [comment]
Hi Dave,

All the decorators fall back to transparent behavior when the buffer allocation fails.
That's probably why you didn't see the effect of the buffer when using a very large size.

Anyway, thanks for the kind words.
Don't forget to [start the project](https://github.com/bblanchon/ArduinoStreamUtils/stargazers) to show your support 👍 

Best regards,
Benoit
