### ISSUE TITLE
Using Arduino But on other Platforms

### ISSUE THREAD

**Issue by daverathbone** [bblanchon/ArduinoStreamUtils#26]
Hi Beniot, 
Many thanks for your hard work on Arduino Json and this stream utils.
I am using your software in a ESP32 IDF only application.
It works fine and Arduino Json at 200K small for my C++ needs. 
However, I do not have Serial.print and Wire as its not in my platform.
Q: Is there any pure Arduino dependancies that will affect my use or is your codeor is it fully platform independant?

Many thanks again

**Comment by bblanchon** [comment]
Hi @daverathbone,

ArduinoJson can be used out of Arduino because it doesn't rely on any Arduino class.

StreamUtils' purpose is to improve Arduino stream classes, so it necessarily depends on them, and it would probably not make much sense to use this library out of Arduino.

Best regards,
Benoit
