### ISSUE TITLE
reference to '__FlashStringHelper' is ambiguous with arduino-pico

### ISSUE THREAD

**Issue by SamHalvoe** [bblanchon/ArduinoStreamUtils#30]
Hello Beniot,

When I include <StreamUtils.h> and compile with the core [arduino-pico](https://github.com/earlephilhower/arduino-pico) I get the error message "reference to '__FlashStringHelper' is ambiguous". If I compile withe core [ArduinoCore-mbed](https://github.com/arduino/ArduinoCore-mbed) I get no error messages.
Reproduction of the error should be possible with an empty sketch, just include <StreamUtils.h> and compile with [arduino-pico](https://github.com/earlephilhower/arduino-pico).
Could you have a look?
Thank you very much.

Best regards,
Samuel

PS: I really like your libraries (ArduinoJSON ans StreamUtils) and bought your ArduinoJSON book some days ago. (:

complete compiler output:
`In file included from c:\Users\samue\OneDrive\Dokumente\Arduino\libraries\StreamUtils\src/StreamUtils.hpp:22,
                 from c:\Users\samue\OneDrive\Dokumente\Arduino\libraries\StreamUtils\src/StreamUtils.h:5,
                 from C:\Users\samue\AppData\Local\Temp\.arduinoIDE-unsaved202324-14884-conkzs.vg2bl\sketch_mar4a\sketch_mar4a.ino:1:
c:\Users\samue\OneDrive\Dokumente\Arduino\libraries\StreamUtils\src/StreamUtils/Streams/ProgmemStream.hpp:22:23: error: reference to '__FlashStringHelper' is ambiguous
   22 |   ProgmemStream(const __FlashStringHelper* ptr)
      |                       ^~~~~~~~~~~~~~~~~~~
In file included from C:\Users\samue\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.0.0\cores\rp2040/api/String.h:2,
                 from c:\users\samue\appdata\local\arduino15\packages\rp2040\hardware\rp2040\3.0.0\arduinocore-api\api\IPAddress.h:23,
                 from c:\users\samue\appdata\local\arduino15\packages\rp2040\hardware\rp2040\3.0.0\arduinocore-api\api\arduinoapi.h:30,
                 from C:\Users\samue\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.0.0\cores\rp2040/api/ArduinoAPI.h:2,
                 from C:\Users\samue\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.0.0\cores\rp2040/Arduino.h:28,
                 from C:\Users\samue\AppData\Local\Temp\arduino\sketches\C583811E80838008550356A24ED744EB\sketch\sketch_mar4a.ino.cpp:1:
c:\users\samue\appdata\local\arduino15\packages\rp2040\hardware\rp2040\3.0.0\arduinocore-api\api\string.h:44:7: note: candidates are: 'class arduino::__FlashStringHelper'
   44 | class __FlashStringHelper;
      |       ^~~~~~~~~~~~~~~~~~~
In file included from c:\Users\samue\OneDrive\Dokumente\Arduino\libraries\StreamUtils\src/StreamUtils.hpp:22,
                 from c:\Users\samue\OneDrive\Dokumente\Arduino\libraries\StreamUtils\src/StreamUtils.h:5,
                 from C:\Users\samue\AppData\Local\Temp\.arduinoIDE-unsaved202324-14884-conkzs.vg2bl\sketch_mar4a\sketch_mar4a.ino:1:
c:\Users\samue\OneDrive\Dokumente\Arduino\libraries\StreamUtils\src/StreamUtils/Streams/ProgmemStream.hpp:11:7: note:                 'class __FlashStringHelper'
   11 | class __FlashStringHelper;
      |       ^~~~~~~~~~~~~~~~~~~

exit status 1

Compilation error: exit status 1`

**Comment by bblanchon** [comment]
Hi Samiel,

Thank you very much for reporting this bug and for purchasing my book 👍 
I just published StreamUtils 1.7.2 to address this issue; it should be available in the Library Manager within a few hours.

Best regards,
Benoit
